# Default VM Templates
# This file contains predefined VM configurations that can be used as templates
# when creating new virtual machines.

templates:
  # Ubuntu 22.04 LTS (Jammy Jellyfish)
  ubuntu-2204:
    name: "ubuntu-2204"
    description: "Ubuntu 22.04 LTS (Jammy Jellyfish) with minimal installation"
    os_type: "Ubuntu_64"
    memory_mb: 4096
    cpu_count: 2
    vram_mb: 16
    storage_gb: 20
    network:
      adapter1: "nat"
      adapter1_type: "82540EM"
    storage_controllers:
      - name: "SATA Controller"
        type: "IntelAhci"
        port_count: 2
    iso_path: ""  # Set path to Ubuntu 22.04 ISO
    boot_order: ["dvd", "disk", "none"]
    
  # Windows 10
  windows-10:
    name: "windows-10"
    description: "Windows 10 (64-bit) with default settings"
    os_type: "Windows10_64"
    memory_mb: 8192
    cpu_count: 4
    vram_mb: 128
    storage_gb: 50
    network:
      adapter1: "nat"
      adapter1_type: "82545EM"
    storage_controllers:
      - name: "SATA Controller"
        type: "IntelAhci"
        port_count: 2
    iso_path: ""  # Set path to Windows 10 ISO
    boot_order: ["dvd", "disk", "none"]
    
  # Debian 11 (Bullseye)
  debian-11:
    name: "debian-11"
    description: "Debian 11 (Bullseye) with XFCE desktop"
    os_type: "Debian_64"
    memory_mb: 4096
    cpu_count: 2
    vram_mb: 16
    storage_gb: 25
    network:
      adapter1: "nat"
      adapter1_type: "82540EM"
    storage_controllers:
      - name: "SATA Controller"
        type: "IntelAhci"
        port_count: 2
    iso_path: ""  # Set path to Debian 11 ISO
    boot_order: ["dvd", "disk", "none"]
    
  # Windows Server 2022
  windows-server-2022:
    name: "windows-server-2022"
    description: "Windows Server 2022 (64-bit) Standard Edition"
    os_type: "Windows2022_64"
    memory_mb: 16384
    cpu_count: 4
    vram_mb: 128
    storage_gb: 100
    network:
      adapter1: "nat"
      adapter1_type: "82545EM"
    storage_controllers:
      - name: "SATA Controller"
        type: "IntelAhci"
        port_count: 4
    iso_path: ""  # Set path to Windows Server 2022 ISO
    boot_order: ["dvd", "disk", "none"]
    
  # Ubuntu Server 22.04 LTS
  ubuntu-server-2204:
    name: "ubuntu-server-2204"
    description: "Ubuntu Server 22.04 LTS (Jammy Jellyfish)"
    os_type: "Ubuntu_64"
    memory_mb: 2048
    cpu_count: 2
    vram_mb: 16
    storage_gb: 20
    network:
      adapter1: "nat"
      adapter1_type: "82540EM"
    storage_controllers:
      - name: "SATA Controller"
        type: "IntelAhci"
        port_count: 2
    iso_path: ""  # Set path to Ubuntu Server 22.04 ISO
    boot_order: ["dvd", "disk", "none"]



