name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        exclude:
          # Skip Python 3.8 on Windows due to VirtualBox compatibility
          - os: windows-latest
            python-version: '3.8'

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Verify test setup
      run: |
        uv run python -c "import pytest; print('pytest version:', pytest.__version__)"
        uv run python -c "import virtualization_mcp; print('virtualization_mcp imported successfully')"
    
    - name: Run tests
      run: |
        uv run pytest tests/ -v --cov=virtualization_mcp --cov-report=xml
    
    - name: Upload coverage to Codecov
      if: github.event_name == 'push' && matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build-dxt:
    name: Build DXT Package
    needs: test
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv sync --dev
        npm install -g @anthropic-ai/mcpb
    
    - name: Build MCPB package
      run: |
        mcpb pack . dist/virtualization-mcp-v1.0.0.mcpb
    
    - name: Upload MCPB package
      uses: actions/upload-artifact@v4
      with:
        name: virtualization-mcp-mcpb-package
        path: dist/*.mcpb
    
    - name: Create GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.mcpb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



